/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.kfstudio.main;

import com.formdev.flatlaf.FlatIntelliJLaf;
import java.awt.List;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author alejandro
 */
public class MainFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrame.class.getName());

    /**
     * Creates new form MainFrame
     */
    
    public MainFrame() {
        BancoDados.carregarMateriais(false);
        BancoDados.carregarCautelas(true);
        initComponents();
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabelaMenus = new javax.swing.JTabbedPane();
        cautelaP = new javax.swing.JPanel();
        materialCoB = new javax.swing.JComboBox<>();
        militarL = new javax.swing.JLabel();
        pgCoB = new javax.swing.JComboBox<>();
        militarTF = new javax.swing.JTextField();
        militarL1 = new javax.swing.JLabel();
        qntCautS = new javax.swing.JSpinner();
        militarL2 = new javax.swing.JLabel();
        obsSP = new javax.swing.JScrollPane();
        obsTA = new javax.swing.JTextArea();
        tituloPanelL1 = new javax.swing.JLabel();
        cautelaB = new javax.swing.JButton();
        dataCautelaChB = new javax.swing.JCheckBox();
        dataCautelaFTF = new javax.swing.JFormattedTextField();
        descautelaP = new javax.swing.JPanel();
        cautelasCoB = new javax.swing.JComboBox<>();
        militarL3 = new javax.swing.JLabel();
        pgTF1 = new javax.swing.JTextField();
        qntL1 = new javax.swing.JLabel();
        qntCautS2 = new javax.swing.JSpinner();
        obsL1 = new javax.swing.JLabel();
        obsSP1 = new javax.swing.JScrollPane();
        obsTF1 = new javax.swing.JTextArea();
        tituloPanelL2 = new javax.swing.JLabel();
        descautelaB = new javax.swing.JButton();
        descautelaChB = new javax.swing.JCheckBox();
        dataDescautelaFTF = new javax.swing.JFormattedTextField();
        militarTF1 = new javax.swing.JTextField();
        addMatP = new javax.swing.JPanel();
        tituloPanelL = new javax.swing.JLabel();
        nomeMatL = new javax.swing.JLabel();
        nomeMatTF = new javax.swing.JTextField();
        tipoMatL = new javax.swing.JLabel();
        tipoMatCoB = new javax.swing.JComboBox<>();
        sitCargaL = new javax.swing.JLabel();
        sitCargaChB = new javax.swing.JCheckBox();
        qntPrevistaL = new javax.swing.JLabel();
        qntPrevistaS = new javax.swing.JSpinner();
        qntExistenteL = new javax.swing.JLabel();
        qntExistenteS = new javax.swing.JSpinner();
        addMatB = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SiGMa");
        setResizable(false);

        materialCoB.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        materialCoB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Material" }));
        materialCoB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                materialCoBActionPerformed(evt);
            }
        });

        militarL.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        militarL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        militarL.setText("Militar que irá cautelar o material");

        pgCoB.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        pgCoB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CEL", "MAJ", "CAP", "1°TEN", "2°TEN", "STEN", "1°SGT", "2°SGT", "3°SGT", "CB EP", "SD EP", "SD EV" }));

        militarTF.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        militarTF.setToolTipText("Nome");
        militarTF.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        militarTF.setName(""); // NOI18N
        militarTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                militarTFActionPerformed(evt);
            }
        });

        militarL1.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        militarL1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        militarL1.setText("Quantidade");

        qntCautS.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N

        militarL2.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        militarL2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        militarL2.setText("Observações");

        obsTA.setColumns(20);
        obsTA.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        obsTA.setRows(5);
        obsSP.setViewportView(obsTA);

        tituloPanelL1.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        tituloPanelL1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloPanelL1.setText("Menu de Cautela");

        cautelaB.setFont(new java.awt.Font("Liberation Sans", 1, 20)); // NOI18N
        cautelaB.setText("Cautelar");
        cautelaB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cautelaBActionPerformed(evt);
            }
        });

        dataCautelaChB.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        dataCautelaChB.setSelected(true);
        dataCautelaChB.setText("Cautelado Hoje?");
        dataCautelaChB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dataCautelaChB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataCautelaChBActionPerformed(evt);
            }
        });

        dataCautelaFTF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        dataCautelaFTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        dataCautelaFTF.setText("dd/mm/yyyy");
        dataCautelaFTF.setEnabled(false);
        dataCautelaFTF.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N

        javax.swing.GroupLayout cautelaPLayout = new javax.swing.GroupLayout(cautelaP);
        cautelaP.setLayout(cautelaPLayout);
        cautelaPLayout.setHorizontalGroup(
            cautelaPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cautelaPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cautelaPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(materialCoB, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tituloPanelL1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(cautelaPLayout.createSequentialGroup()
                        .addGroup(cautelaPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(cautelaPLayout.createSequentialGroup()
                                .addComponent(pgCoB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(militarTF, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(militarL2, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(obsSP, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(militarL, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(cautelaPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(cautelaPLayout.createSequentialGroup()
                                .addGap(179, 179, 179)
                                .addGroup(cautelaPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dataCautelaFTF)
                                    .addGroup(cautelaPLayout.createSequentialGroup()
                                        .addComponent(militarL1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cautelaPLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(qntCautS, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cautelaPLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(cautelaPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cautelaPLayout.createSequentialGroup()
                                        .addComponent(cautelaB, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(23, 23, 23))
                                    .addComponent(dataCautelaChB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
        );
        cautelaPLayout.setVerticalGroup(
            cautelaPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cautelaPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloPanelL1, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(materialCoB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(cautelaPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cautelaPLayout.createSequentialGroup()
                        .addComponent(militarL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(cautelaPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(militarTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pgCoB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(militarL2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(obsSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(cautelaPLayout.createSequentialGroup()
                        .addComponent(militarL1)
                        .addGap(15, 15, 15)
                        .addComponent(qntCautS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(dataCautelaChB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dataCautelaFTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cautelaB, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lerMateriais();

        jTabelaMenus.addTab("Cautelar", cautelaP);

        cautelasCoB.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        cautelasCoB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cautela" }));
        cautelasCoB.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cautelasCoBPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        militarL3.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        militarL3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        militarL3.setText("Militar que cautelou o material");

        pgTF1.setEditable(false);
        pgTF1.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        pgTF1.setToolTipText("Nome");
        pgTF1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        pgTF1.setName(""); // NOI18N
        pgTF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pgTF1ActionPerformed(evt);
            }
        });

        qntL1.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        qntL1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        qntL1.setText("Unidades Descauteladas");

        qntCautS2.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N

        obsL1.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        obsL1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        obsL1.setText("Observações");

        obsTF1.setEditable(false);
        obsTF1.setColumns(20);
        obsTF1.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        obsTF1.setRows(5);
        obsSP1.setViewportView(obsTF1);

        tituloPanelL2.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        tituloPanelL2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloPanelL2.setText("Menu de Descautela");

        descautelaB.setFont(new java.awt.Font("Liberation Sans", 1, 20)); // NOI18N
        descautelaB.setText("Descautelar");
        descautelaB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descautelaBActionPerformed(evt);
            }
        });

        descautelaChB.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        descautelaChB.setSelected(true);
        descautelaChB.setText("Descautelado Hoje?");
        descautelaChB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        descautelaChB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descautelaChBActionPerformed(evt);
            }
        });

        dataDescautelaFTF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        dataDescautelaFTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        dataDescautelaFTF.setText("dd/mm/yyyy");
        dataDescautelaFTF.setEnabled(false);
        dataDescautelaFTF.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N

        militarTF1.setEditable(false);
        militarTF1.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        militarTF1.setToolTipText("Nome");
        militarTF1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        militarTF1.setName(""); // NOI18N
        militarTF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                militarTF1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout descautelaPLayout = new javax.swing.GroupLayout(descautelaP);
        descautelaP.setLayout(descautelaPLayout);
        descautelaPLayout.setHorizontalGroup(
            descautelaPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(descautelaPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(descautelaPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cautelasCoB, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tituloPanelL2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(descautelaPLayout.createSequentialGroup()
                        .addGroup(descautelaPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(obsL1, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(obsSP1, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(militarL3, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(descautelaPLayout.createSequentialGroup()
                                .addComponent(pgTF1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(militarTF1)))
                        .addGroup(descautelaPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(descautelaPLayout.createSequentialGroup()
                                .addGap(179, 179, 179)
                                .addGroup(descautelaPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dataDescautelaFTF)
                                    .addGroup(descautelaPLayout.createSequentialGroup()
                                        .addComponent(qntL1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, descautelaPLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(qntCautS2, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, descautelaPLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(descautelaPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, descautelaPLayout.createSequentialGroup()
                                        .addComponent(descautelaB, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(23, 23, 23))
                                    .addComponent(descautelaChB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
        );
        descautelaPLayout.setVerticalGroup(
            descautelaPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(descautelaPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloPanelL2, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(cautelasCoB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(descautelaPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(descautelaPLayout.createSequentialGroup()
                        .addComponent(militarL3)
                        .addGap(18, 18, 18)
                        .addGroup(descautelaPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pgTF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(militarTF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addComponent(obsL1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(obsSP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(descautelaPLayout.createSequentialGroup()
                        .addComponent(qntL1)
                        .addGap(15, 15, 15)
                        .addComponent(qntCautS2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(descautelaChB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dataDescautelaFTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(descautelaB, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lerCautelas();

        jTabelaMenus.addTab("Descautelar", descautelaP);

        tituloPanelL.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        tituloPanelL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloPanelL.setText("Adicionar Material ao Banco de Dados");

        nomeMatL.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        nomeMatL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nomeMatL.setText("Nome e Descrição do Material");

        nomeMatTF.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        nomeMatTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nomeMatTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeMatTFActionPerformed(evt);
            }
        });

        tipoMatL.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        tipoMatL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tipoMatL.setText("Tipo de Material");

        tipoMatCoB.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        tipoMatCoB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fardamento", "Campanha", "Dia-a-Dia", "Rádio", "Alojamento", "Tático" }));

        sitCargaL.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        sitCargaL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sitCargaL.setText("Situação Carga");

        sitCargaChB.setFont(new java.awt.Font("Liberation Sans", 2, 18)); // NOI18N
        sitCargaChB.setSelected(true);
        sitCargaChB.setText("Materal Presente na Carga?");
        sitCargaChB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sitCargaChBActionPerformed(evt);
            }
        });

        qntPrevistaL.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        qntPrevistaL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        qntPrevistaL.setText("Quantidade Prevista");

        qntPrevistaS.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N

        qntExistenteL.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        qntExistenteL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        qntExistenteL.setText("Quantidade Existente");

        qntExistenteS.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N

        addMatB.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        addMatB.setText("Add Material");
        addMatB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMatBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addMatPLayout = new javax.swing.GroupLayout(addMatP);
        addMatP.setLayout(addMatPLayout);
        addMatPLayout.setHorizontalGroup(
            addMatPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addMatPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addMatPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tituloPanelL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nomeMatL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
                    .addComponent(nomeMatTF, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addMatPLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(addMatPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(qntPrevistaS, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(qntPrevistaL, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(addMatPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(qntExistenteS, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(qntExistenteL, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12))
                    .addGroup(addMatPLayout.createSequentialGroup()
                        .addGroup(addMatPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tipoMatCoB, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tipoMatL, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(addMatPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(sitCargaChB)
                            .addGroup(addMatPLayout.createSequentialGroup()
                                .addComponent(sitCargaL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(12, 12, 12)))))
                .addContainerGap())
            .addGroup(addMatPLayout.createSequentialGroup()
                .addGap(284, 284, 284)
                .addComponent(addMatB, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        addMatPLayout.setVerticalGroup(
            addMatPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addMatPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloPanelL, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(nomeMatL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomeMatTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(addMatPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipoMatL)
                    .addComponent(sitCargaL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addMatPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipoMatCoB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sitCargaChB))
                .addGap(18, 18, 18)
                .addGroup(addMatPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(qntExistenteL)
                    .addComponent(qntPrevistaL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addMatPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(qntExistenteS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(qntPrevistaS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(addMatB, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        jTabelaMenus.addTab("Add. Material", addMatP);

        jMenu1.setText("FIle");

        jMenu3.setText("Banco Dados");

        jMenuItem1.setText("Verificar Banco Dados");
        jMenu3.add(jMenuItem1);

        jMenu1.add(jMenu3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabelaMenus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabelaMenus, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabelaMenus.getAccessibleContext().setAccessibleName("Cautelar");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nomeMatTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeMatTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeMatTFActionPerformed

    private void sitCargaChBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sitCargaChBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sitCargaChBActionPerformed

    private void addMatBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMatBActionPerformed
        String nomeMat = nomeMatTF.getText();
        String tipoMat = tipoMatCoB.getSelectedItem().toString();
        int qntPrevisto = (int)qntPrevistaS.getValue();
        int qntExistente = (int)qntExistenteS.getValue();
        boolean sitCarga = sitCargaChB.isSelected();
        Material tempMat = new Material(nomeMat,tipoMat,qntPrevisto,qntExistente,sitCarga);
        BancoDados.addMatTabela(tempMat, addMatP,true);
        lerMateriais();
        tempMat = null;
    }//GEN-LAST:event_addMatBActionPerformed

    private void cautelaBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cautelaBActionPerformed
        Cautela caut = new Cautela();
        caut.setMaterialId(Integer.parseInt(materialCoB.getSelectedItem().toString().substring(0, 1)));
        caut.setPg(pgCoB.getSelectedItem().toString());
        caut.setNome(militarTF.getText().toUpperCase());
        if((int)qntCautS.getValue() <= 0){
            JOptionPane.showMessageDialog(rootPane, "Insira uma quantidade maior que 0 para cautelar");
            return;
        }else if((int)qntCautS.getValue() > BancoDados.getMaterial(Integer.parseInt(materialCoB.getSelectedItem().toString().substring(0, 1))).getSaldo()){
            JOptionPane.showMessageDialog(rootPane, "Você está tentando cautelar mais material do que há disponívelí");
            return;
        }
        caut.setQnt((int)qntCautS.getValue());
        caut.setObs(obsTA.getText());
        LocalDate dataCautela;
        if(!dataCautelaChB.isSelected()){
            String data = dataCautelaFTF.getText().replaceAll("/", "");
            if(!data.matches("\\d+")){
                JOptionPane.showMessageDialog(rootPane, "Utilize apenas numeros na data de cautela");
                return;
            }
            int dia = Integer.parseInt(data.substring(0, 2));
            int mes = Integer.parseInt(data.substring(2, 4));
            int ano = Integer.parseInt(data.substring(4, 8));
            dataCautela = LocalDate.of(ano, mes, dia);
            if(dataCautela.isAfter(LocalDate.now())){
               JOptionPane.showMessageDialog(rootPane, "Insira uma data válida");
               return;
            }
            
        }
        dataCautela = LocalDate.now();
        caut.setData_cautela(dataCautela);
        BancoDados.addCautela(caut, addMatP, true);
        lerMateriais();
        lerCautelas();
        
    }//GEN-LAST:event_cautelaBActionPerformed

    private void militarTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_militarTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_militarTFActionPerformed

    private void materialCoBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_materialCoBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_materialCoBActionPerformed

    private void descautelaBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descautelaBActionPerformed
        
        Cautela caut = BancoDados.getCautela(Integer.parseInt(cautelasCoB.getSelectedItem().toString().substring(0, 1)));
        if((int)qntCautS2.getValue() < 1){
            JOptionPane.showMessageDialog(rootPane, "Insira uma quantidade maior que zero!");
            return;
        }else if((int)qntCautS2.getValue() > caut.getQnt()){
            JOptionPane.showMessageDialog(rootPane, "Insira um valor inferior ou igual a quantidade cautelada!");
            return;
        }
        if(caut.descautelar((int)qntCautS2.getValue())){
            JOptionPane.showMessageDialog(rootPane, "Material descautelado com sucesso!");
        }else {
            JOptionPane.showMessageDialog(rootPane, "Foram descauteladas " + (int)qntCautS2.getValue() + " unidades\nRestam " + caut.getQnt() + " unidades");
        }
        lerMateriais();
        lerCautelas();
    }//GEN-LAST:event_descautelaBActionPerformed

    private void pgTF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pgTF1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pgTF1ActionPerformed

    private void militarTF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_militarTF1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_militarTF1ActionPerformed

    private void dataCautelaChBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataCautelaChBActionPerformed
        dataCautelaFTF.setEnabled(!dataCautelaChB.isSelected());
    }//GEN-LAST:event_dataCautelaChBActionPerformed

    private void descautelaChBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descautelaChBActionPerformed
        dataDescautelaFTF.setEnabled(!descautelaChB.isSelected());
    }//GEN-LAST:event_descautelaChBActionPerformed

    private void cautelasCoBPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cautelasCoBPopupMenuWillBecomeInvisible
        
        if(!cautelasCoB.getSelectedItem().toString().substring(0, 1).matches("\\d")){
            pgTF1.setText("");
            militarTF1.setText("");
            obsTF1.setText("");
            return;
        }
        Cautela caut = BancoDados.getCautela(Integer.parseInt(cautelasCoB.getSelectedItem().toString().substring(0, 1)));
        pgTF1.setText(caut.getPg());
        militarTF1.setText(caut.getNome());
        obsTF1.setText(caut.getObs());
    }//GEN-LAST:event_cautelasCoBPopupMenuWillBecomeInvisible

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(new FlatIntelliJLaf());
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainFrame().setVisible(true));
    }
    
    private void lerMateriais(){
        materialCoB.removeAllItems();
        materialCoB.addItem("Material");
        Material mat = null;
        for(int i = 1; i <= BancoDados.getListSize(Material.class); i++){
            mat = BancoDados.getMaterial(i);
            if(mat.getSaldo() > 0){
                materialCoB.addItem(mat.getId()+" | Saldo: " + mat.getSaldo() + " | " + mat.getMaterial());
            }
}
    }
    
    private void lerCautelas(){
        cautelasCoB.removeAllItems();
        cautelasCoB.addItem("Cautelas");
        Cautela caut = null;
        for(int i = 1; i <= BancoDados.getListSize(Cautela.class); i++){
            caut = BancoDados.getCautela(i);
            if(caut != null && caut.getSit_cautela())
                cautelasCoB.addItem(caut.getId() + " | " + caut.getMaterialName() + " | Qnt: " + caut.getQnt() + " | "+caut.getPg() +" "+ caut.getNome()+" | Data: " + caut.getData_cautela());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addMatB;
    private javax.swing.JPanel addMatP;
    private javax.swing.JButton cautelaB;
    private javax.swing.JPanel cautelaP;
    private javax.swing.JComboBox<String> cautelasCoB;
    private javax.swing.JCheckBox dataCautelaChB;
    private javax.swing.JFormattedTextField dataCautelaFTF;
    private javax.swing.JFormattedTextField dataDescautelaFTF;
    private javax.swing.JButton descautelaB;
    private javax.swing.JCheckBox descautelaChB;
    private javax.swing.JPanel descautelaP;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JTabbedPane jTabelaMenus;
    private javax.swing.JComboBox<String> materialCoB;
    private javax.swing.JLabel militarL;
    private javax.swing.JLabel militarL1;
    private javax.swing.JLabel militarL2;
    private javax.swing.JLabel militarL3;
    private javax.swing.JTextField militarTF;
    private javax.swing.JTextField militarTF1;
    private javax.swing.JLabel nomeMatL;
    private javax.swing.JTextField nomeMatTF;
    private javax.swing.JLabel obsL1;
    private javax.swing.JScrollPane obsSP;
    private javax.swing.JScrollPane obsSP1;
    private javax.swing.JTextArea obsTA;
    private javax.swing.JTextArea obsTF1;
    private javax.swing.JComboBox<String> pgCoB;
    private javax.swing.JTextField pgTF1;
    private javax.swing.JSpinner qntCautS;
    private javax.swing.JSpinner qntCautS2;
    private javax.swing.JLabel qntExistenteL;
    private javax.swing.JSpinner qntExistenteS;
    private javax.swing.JLabel qntL1;
    private javax.swing.JLabel qntPrevistaL;
    private javax.swing.JSpinner qntPrevistaS;
    private javax.swing.JCheckBox sitCargaChB;
    private javax.swing.JLabel sitCargaL;
    private javax.swing.JComboBox<String> tipoMatCoB;
    private javax.swing.JLabel tipoMatL;
    private javax.swing.JLabel tituloPanelL;
    private javax.swing.JLabel tituloPanelL1;
    private javax.swing.JLabel tituloPanelL2;
    // End of variables declaration//GEN-END:variables
}
