/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.kfstudio.main;

import com.formdev.flatlaf.FlatIntelliJLaf;
import java.awt.List;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.UIManager;

/**
 *
 * @author alejandro
 */
public class MainFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrame.class.getName());

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        BancoDados.carregarMateriais();
        BancoDados.carregarCautelas();
        initComponents();
        System.out.println(BancoDados.getCautela(1));
    }
    
    private void setComponents(){
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabelaMenus = new javax.swing.JTabbedPane();
        cautelaP = new javax.swing.JPanel();
        materialCoB = new javax.swing.JComboBox<>();
        militarL = new javax.swing.JLabel();
        pgCoB = new javax.swing.JComboBox<>();
        militarTF = new javax.swing.JTextField();
        militarL1 = new javax.swing.JLabel();
        qntPrevistaS1 = new javax.swing.JSpinner();
        militarL2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        tituloPanelL1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        descautelaP = new javax.swing.JPanel();
        materialCoB1 = new javax.swing.JComboBox<>();
        militarL3 = new javax.swing.JLabel();
        militarTF1 = new javax.swing.JTextField();
        militarL4 = new javax.swing.JLabel();
        qntPrevistaS2 = new javax.swing.JSpinner();
        militarL5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        tituloPanelL2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jCheckBox2 = new javax.swing.JCheckBox();
        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        militarTF2 = new javax.swing.JTextField();
        addMatP = new javax.swing.JPanel();
        tituloPanelL = new javax.swing.JLabel();
        nomeMatL = new javax.swing.JLabel();
        nomeMatTF = new javax.swing.JTextField();
        tipoMatL = new javax.swing.JLabel();
        tipoMatCoB = new javax.swing.JComboBox<>();
        sitCargaL = new javax.swing.JLabel();
        sitCargaChB = new javax.swing.JCheckBox();
        qntPrevistaL = new javax.swing.JLabel();
        qntPrevistaS = new javax.swing.JSpinner();
        qntExistenteL = new javax.swing.JLabel();
        qntExistenteS = new javax.swing.JSpinner();
        addMatB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SiGMa");
        setResizable(false);

        materialCoB.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        materialCoB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Material" }));
        materialCoB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                materialCoBActionPerformed(evt);
            }
        });

        militarL.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        militarL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        militarL.setText("Militar que irá cautelar o material");

        pgCoB.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        pgCoB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cel", "Maj", "Cap", "1°Ten", "2°Ten", "STen", "1°Sgt", "2°Sgt", "3°Sgt", "Cb EP", "Sd EP", "Sd EV" }));

        militarTF.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        militarTF.setToolTipText("Nome");
        militarTF.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        militarTF.setName(""); // NOI18N
        militarTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                militarTFActionPerformed(evt);
            }
        });

        militarL1.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        militarL1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        militarL1.setText("Quantidade");

        qntPrevistaS1.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N

        militarL2.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        militarL2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        militarL2.setText("Observações");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        tituloPanelL1.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        tituloPanelL1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloPanelL1.setText("Menu de Cautela");

        jButton1.setFont(new java.awt.Font("Liberation Sans", 1, 20)); // NOI18N
        jButton1.setText("Cautelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jCheckBox1.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jCheckBox1.setSelected(true);
        jCheckBox1.setText("Cautelado Hoje?");
        jCheckBox1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        jFormattedTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField1.setText("dd/mm/yyyy");
        jFormattedTextField1.setEnabled(false);
        jFormattedTextField1.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N

        javax.swing.GroupLayout cautelaPLayout = new javax.swing.GroupLayout(cautelaP);
        cautelaP.setLayout(cautelaPLayout);
        cautelaPLayout.setHorizontalGroup(
            cautelaPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cautelaPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cautelaPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(materialCoB, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tituloPanelL1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(cautelaPLayout.createSequentialGroup()
                        .addGroup(cautelaPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(cautelaPLayout.createSequentialGroup()
                                .addComponent(pgCoB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(militarTF, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(militarL2, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(militarL, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(cautelaPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(cautelaPLayout.createSequentialGroup()
                                .addGap(179, 179, 179)
                                .addGroup(cautelaPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jFormattedTextField1)
                                    .addGroup(cautelaPLayout.createSequentialGroup()
                                        .addComponent(militarL1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cautelaPLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(qntPrevistaS1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cautelaPLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(cautelaPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cautelaPLayout.createSequentialGroup()
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(23, 23, 23))
                                    .addComponent(jCheckBox1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
        );
        cautelaPLayout.setVerticalGroup(
            cautelaPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cautelaPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloPanelL1, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(materialCoB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(cautelaPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cautelaPLayout.createSequentialGroup()
                        .addComponent(militarL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(cautelaPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(militarTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pgCoB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(militarL2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(cautelaPLayout.createSequentialGroup()
                        .addComponent(militarL1)
                        .addGap(15, 15, 15)
                        .addComponent(qntPrevistaS1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBox1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Material mat = null;
        for(int i = 1; i <= BancoDados.getListSize(Material.class); i++){
            mat = BancoDados.getMaterial(i);
            materialCoB.addItem("Saldo: " + mat.getSaldo() + " | " + mat.getMaterial());
        }

        jTabelaMenus.addTab("Cautelar", cautelaP);

        materialCoB1.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        materialCoB1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cautela" }));
        materialCoB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                materialCoB1ActionPerformed(evt);
            }
        });

        militarL3.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        militarL3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        militarL3.setText("Militar que irá cautelar o material");

        militarTF1.setEditable(false);
        militarTF1.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        militarTF1.setToolTipText("Nome");
        militarTF1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        militarTF1.setName(""); // NOI18N
        militarTF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                militarTF1ActionPerformed(evt);
            }
        });

        militarL4.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        militarL4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        militarL4.setText("Quantidade");

        qntPrevistaS2.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        qntPrevistaS2.setEnabled(false);

        militarL5.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        militarL5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        militarL5.setText("Observações");

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        tituloPanelL2.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        tituloPanelL2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloPanelL2.setText("Menu de Descautela");

        jButton2.setFont(new java.awt.Font("Liberation Sans", 1, 20)); // NOI18N
        jButton2.setText("Descautelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jCheckBox2.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jCheckBox2.setSelected(true);
        jCheckBox2.setText("Cautelado Hoje?");
        jCheckBox2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jFormattedTextField2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        jFormattedTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField2.setText("dd/mm/yyyy");
        jFormattedTextField2.setEnabled(false);
        jFormattedTextField2.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N

        militarTF2.setEditable(false);
        militarTF2.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        militarTF2.setToolTipText("Nome");
        militarTF2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        militarTF2.setName(""); // NOI18N
        militarTF2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                militarTF2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout descautelaPLayout = new javax.swing.GroupLayout(descautelaP);
        descautelaP.setLayout(descautelaPLayout);
        descautelaPLayout.setHorizontalGroup(
            descautelaPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(descautelaPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(descautelaPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(materialCoB1, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tituloPanelL2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(descautelaPLayout.createSequentialGroup()
                        .addGroup(descautelaPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(militarL5, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(militarL3, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(descautelaPLayout.createSequentialGroup()
                                .addComponent(militarTF1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(militarTF2)))
                        .addGroup(descautelaPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(descautelaPLayout.createSequentialGroup()
                                .addGap(179, 179, 179)
                                .addGroup(descautelaPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jFormattedTextField2)
                                    .addGroup(descautelaPLayout.createSequentialGroup()
                                        .addComponent(militarL4, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, descautelaPLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(qntPrevistaS2, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, descautelaPLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(descautelaPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, descautelaPLayout.createSequentialGroup()
                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(23, 23, 23))
                                    .addComponent(jCheckBox2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
        );
        descautelaPLayout.setVerticalGroup(
            descautelaPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(descautelaPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloPanelL2, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(materialCoB1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(descautelaPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(descautelaPLayout.createSequentialGroup()
                        .addComponent(militarL3)
                        .addGap(18, 18, 18)
                        .addGroup(descautelaPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(militarTF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(militarTF2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addComponent(militarL5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(descautelaPLayout.createSequentialGroup()
                        .addComponent(militarL4)
                        .addGap(15, 15, 15)
                        .addComponent(qntPrevistaS2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBox2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Cautela caut = null;
        for(int i = 1; i <= BancoDados.getListSize(Cautela.class); i++){
            caut = BancoDados.getCautela(i);
            materialCoB1.addItem("Mil: " + caut.getPg() + "  " + caut.getNome() + " | " + caut.getMaterialName() + " | Qnt: " + caut.getQnt() + " | " + caut.getData_cautela());
        }

        jTabelaMenus.addTab("Descautelar", descautelaP);

        tituloPanelL.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        tituloPanelL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloPanelL.setText("Adicionar Material ao Banco de Dados");

        nomeMatL.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        nomeMatL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nomeMatL.setText("Nome e Descrição do Material");

        nomeMatTF.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        nomeMatTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nomeMatTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeMatTFActionPerformed(evt);
            }
        });

        tipoMatL.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        tipoMatL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tipoMatL.setText("Tipo de Material");

        tipoMatCoB.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        tipoMatCoB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fardamento", "Campanha", "Dia-a-Dia", "Rádio", "Alojamento", "Tático" }));

        sitCargaL.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        sitCargaL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sitCargaL.setText("Situação Carga");

        sitCargaChB.setFont(new java.awt.Font("Liberation Sans", 2, 18)); // NOI18N
        sitCargaChB.setSelected(true);
        sitCargaChB.setText("Materal Presente na Carga?");
        sitCargaChB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sitCargaChBActionPerformed(evt);
            }
        });

        qntPrevistaL.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        qntPrevistaL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        qntPrevistaL.setText("Quantidade Prevista");

        qntPrevistaS.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N

        qntExistenteL.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        qntExistenteL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        qntExistenteL.setText("Quantidade Existente");

        qntExistenteS.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N

        addMatB.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        addMatB.setText("Add Material");
        addMatB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMatBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addMatPLayout = new javax.swing.GroupLayout(addMatP);
        addMatP.setLayout(addMatPLayout);
        addMatPLayout.setHorizontalGroup(
            addMatPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addMatPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addMatPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tituloPanelL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nomeMatL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 717, Short.MAX_VALUE)
                    .addComponent(nomeMatTF, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addMatPLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(addMatPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(qntPrevistaS, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(qntPrevistaL, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(addMatPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(qntExistenteS, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(qntExistenteL, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12))
                    .addGroup(addMatPLayout.createSequentialGroup()
                        .addGroup(addMatPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tipoMatCoB, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tipoMatL, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(addMatPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(addMatPLayout.createSequentialGroup()
                                .addGap(93, 93, 93)
                                .addComponent(sitCargaL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(12, 12, 12))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addMatPLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(sitCargaChB)))))
                .addContainerGap())
            .addGroup(addMatPLayout.createSequentialGroup()
                .addGap(284, 284, 284)
                .addComponent(addMatB, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        addMatPLayout.setVerticalGroup(
            addMatPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addMatPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloPanelL, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(nomeMatL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomeMatTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(addMatPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipoMatL)
                    .addComponent(sitCargaL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addMatPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipoMatCoB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sitCargaChB))
                .addGap(18, 18, 18)
                .addGroup(addMatPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(qntExistenteL)
                    .addComponent(qntPrevistaL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addMatPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(qntExistenteS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(qntPrevistaS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(addMatB, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        jTabelaMenus.addTab("Add. Material", addMatP);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabelaMenus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabelaMenus, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabelaMenus.getAccessibleContext().setAccessibleName("Cautelar");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nomeMatTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeMatTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeMatTFActionPerformed

    private void sitCargaChBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sitCargaChBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sitCargaChBActionPerformed

    private void addMatBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMatBActionPerformed
        String nomeMat = nomeMatTF.getText();
        String tipoMat = tipoMatCoB.getSelectedItem().toString();
        int qntPrevisto = (int)qntPrevistaS.getValue();
        int qntExistente = (int)qntExistenteS.getValue();
        boolean sitCarga = sitCargaChB.isSelected();
        Material tempMat = new Material(nomeMat,tipoMat,qntPrevisto,qntExistente,sitCarga);
        BancoDados.addMatTabela(tempMat, addMatP);
        tempMat = null;
    }//GEN-LAST:event_addMatBActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void militarTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_militarTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_militarTFActionPerformed

    private void materialCoBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_materialCoBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_materialCoBActionPerformed

    private void materialCoB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_materialCoB1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_materialCoB1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void militarTF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_militarTF1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_militarTF1ActionPerformed

    private void militarTF2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_militarTF2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_militarTF2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(new FlatIntelliJLaf());
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addMatB;
    private javax.swing.JPanel addMatP;
    private javax.swing.JPanel cautelaP;
    private javax.swing.JPanel descautelaP;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabelaMenus;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JComboBox<String> materialCoB;
    private javax.swing.JComboBox<String> materialCoB1;
    private javax.swing.JLabel militarL;
    private javax.swing.JLabel militarL1;
    private javax.swing.JLabel militarL2;
    private javax.swing.JLabel militarL3;
    private javax.swing.JLabel militarL4;
    private javax.swing.JLabel militarL5;
    private javax.swing.JTextField militarTF;
    private javax.swing.JTextField militarTF1;
    private javax.swing.JTextField militarTF2;
    private javax.swing.JLabel nomeMatL;
    private javax.swing.JTextField nomeMatTF;
    private javax.swing.JComboBox<String> pgCoB;
    private javax.swing.JLabel qntExistenteL;
    private javax.swing.JSpinner qntExistenteS;
    private javax.swing.JLabel qntPrevistaL;
    private javax.swing.JSpinner qntPrevistaS;
    private javax.swing.JSpinner qntPrevistaS1;
    private javax.swing.JSpinner qntPrevistaS2;
    private javax.swing.JCheckBox sitCargaChB;
    private javax.swing.JLabel sitCargaL;
    private javax.swing.JComboBox<String> tipoMatCoB;
    private javax.swing.JLabel tipoMatL;
    private javax.swing.JLabel tituloPanelL;
    private javax.swing.JLabel tituloPanelL1;
    private javax.swing.JLabel tituloPanelL2;
    // End of variables declaration//GEN-END:variables
}
